// Generated by CoffeeScript 1.7.1
var FormRenderExt, HorizontalTitleRender, LineRenderExt, PageRenderExt, PagerRenderExt, Render, Sender, TextFieldRenderExt,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Render = (function(_super) {
  __extends(Render, _super);

  function Render() {
    return Render.__super__.constructor.apply(this, arguments);
  }

  return Render;

})(RenderizerAbstract);

Sender = (function(_super) {
  __extends(Sender, _super);

  function Sender() {
    return Sender.__super__.constructor.apply(this, arguments);
  }

  return Sender;

})(SenderAbstract);

HorizontalTitleRender = (function(_super) {
  __extends(HorizontalTitleRender, _super);

  function HorizontalTitleRender() {
    return HorizontalTitleRender.__super__.constructor.apply(this, arguments);
  }

  HorizontalTitleRender.prototype.createElement = function(def, renderizer) {
    return document.createElement('h3');
  };

  return HorizontalTitleRender;

})(SpecificElementRender);

TextFieldRenderExt = (function(_super) {
  __extends(TextFieldRenderExt, _super);

  function TextFieldRenderExt() {
    return TextFieldRenderExt.__super__.constructor.apply(this, arguments);
  }

  TextFieldRenderExt.prototype.createElement = function(def, renderizer) {
    var ret;
    ret = TextFieldRenderExt.__super__.createElement.call(this, def, renderizer);
    this.element = def;
    $(def.obj_field).addClass('ui-widget-input');
    return ret;
  };

  return TextFieldRenderExt;

})(TextFieldRender);

FormRenderExt = (function(_super) {
  __extends(FormRenderExt, _super);

  function FormRenderExt() {
    return FormRenderExt.__super__.constructor.apply(this, arguments);
  }

  FormRenderExt.prototype.createElement = function(def, renderizer) {
    var ret;
    ret = FormRenderExt.__super__.createElement.call(this, def, renderizer);
    this.element = def;
    this.component = ret;
    $('body').addClass('ui-widget-content');
    $('body').addClass('noborder');
    return ret;
  };

  FormRenderExt.prototype.startElement = function(def, renderizer) {
    var ret;
    ret = FormRenderExt.__super__.startElement.call(this, def, renderizer);
    $(this.component).height(screen.availHeight);
    $(this.component).addClass('noborder');
    return ret;
  };

  return FormRenderExt;

})(FormRender);

LineRenderExt = (function(_super) {
  __extends(LineRenderExt, _super);

  function LineRenderExt() {
    return LineRenderExt.__super__.constructor.apply(this, arguments);
  }

  LineRenderExt.prototype.createElement = function(def, renderizer) {
    var ret;
    ret = LineRenderExt.__super__.createElement.call(this, def, renderizer);
    this.element = def;
    $(ret).addClass('ui-widget');
    return ret;
  };

  return LineRenderExt;

})(LineRender);

PageRenderExt = (function(_super) {
  __extends(PageRenderExt, _super);

  function PageRenderExt() {
    return PageRenderExt.__super__.constructor.apply(this, arguments);
  }

  PageRenderExt.prototype.beforeStartChildren = function(def, renderizer) {
    if (def.width) {
      return def.setWidth(def.width);
    }
  };

  return PageRenderExt;

})(PageRender);

PagerRenderExt = (function(_super) {
  __extends(PagerRenderExt, _super);

  function PagerRenderExt() {
    return PagerRenderExt.__super__.constructor.apply(this, arguments);
  }

  PagerRenderExt.prototype.startElement = function(def, renderizer) {
    return PagerRenderExt.__super__.startElement.call(this, def, renderizer);
  };

  PagerRenderExt.prototype.afterAllStart = function(def, renderizer) {
    var child, _i, _len, _ref, _results;
    $('#' + def.id).tabs({
      heightStyle: "fill"
    });
    _ref = def.children;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      child = _ref[_i];
      _results.push($(child.component).removeClass('ui-tabs-panel'));
    }
    return _results;
  };

  PagerRenderExt.prototype.activate = function(event, ui, def) {
    return def.start(this);
  };

  return PagerRenderExt;

})(PagerRender);
