// Generated by CoffeeScript 1.7.1
var Render, Sender;

Render = (function() {
  function Render(parent) {
    this.parent = parent;
    console.log('design render');
  }

  return Render;

})();

Sender = (function() {
  function Sender(parent) {
    this.parent = parent;
    console.log('design sender');
  }

  return Sender;

})();
